newrelic/newrelic-android-agent

README.md, roadmap.md
For OSS public release.
These is the same changes already merged into `develop`.
=> [NR-24637] Migrate top-level docs ahead of develop

agent-core/src/main/java/com/newrelic/agent/android/analytics/NetworkRequestEvent.java, agent-core/src/test/java/com/newrelic/agent/android/analytics/NetworkRequestEventTest.java
[Fix] Added Map Parameters in NetworkRequestEvent While Data are sending for HttpRequests
=> [NR-147490] Map Parameters are not sending for Http Instrumentation

plugins/gradle/src/functional/groovy/com/newrelic/agent/android/PluginJDK11SmokeSpec.groovy, plugins/gradle/src/functional/groovy/com/newrelic/agent/android/PluginJDK17SmokeSpec.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/NewRelicConfigTask.groovy
Normalized name breaks ingest crash/Hex deobfuscation. 
Updated tests.
=> [NR-156833] Revert obfuscation flag name in embedded NewRelicConfig class

README.md
The change to README foro repolinter fix was committed to main, rather than develop.
=> fix: backport main commits into develop

.github/workflows/functionalTests.yml, plugins/gradle/build.gradle
Workflow is run new pull request against either develop or main branches. At present, only the `functional-regressions-jdk17` job is enabled. Test reports are archived as job artifacts, with 3 day retention.
The task `plugins:gradle:functionalTests` is added as a dependency of the default `check` task.
=> chore: re-enable plugin functional tests

gradle.properties, plugins/gradle/build.gradle, plugins/gradle/src/integration/groovy/com/newrelic/agent/android/VariantAdapterTest.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/VariantAdapter.groovy
Transform API is still available to those using Gradle 7.4.0 and below, so default to that for AGP 7.3, 7.2 and lower.
=> [NR-163742] AGP 7.2, 7.3 must use legacy class transformer

instrumentation/src/main/java/com/newrelic/agent/compile/visitor/AgentDelegateClassVisitor.java
Problem was a typo, really, but adds assignment of superName in ctor.
=> fix: Fragment instrumentation broken by refactoring

agent-core/src/main/java/com/newrelic/agent/android/HttpHeaders.java, agent-core/src/main/java/com/newrelic/agent/android/api/common/TransactionData.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/HttpURLConnectionExtension.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/HttpsURLConnectionExtension.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/TransactionState.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/TransactionStateUtil.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp2/OkHttp2Instrumentation.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp2/OkHttp2TransactionStateUtil.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3Instrumentation.java, agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtil.java, agent-core/src/main/java/com/newrelic/agent/android/util/Constants.java, agent-core/src/test/java/com/newrelic/agent/android/HttpHeadersTest.java, agent-core/src/test/java/com/newrelic/agent/android/instrumentation/HttpURLConnectionExtensionTest.java, agent-core/src/test/java/com/newrelic/agent/android/instrumentation/HttpsURLConnectionExtensionTest.java, agent-core/src/test/java/com/newrelic/agent/android/instrumentation/okhttp2/OkHttp2TransactionStateUtilTest.java, agent-core/src/test/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtilTest.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java
1) implemented a new feature to track HTTP headers that are added by the client when making an HTTP request. To achieve this, we added a static method that records these headers and adds them as custom attributes at the HTTP request level.
2) added a new feature to capture Apollo GraphQL HTTP headers, specifically related to the operation name, type, and ID. By capturing these headers, we can provide more granular insights into how GraphQL is being used, empowering our customers to gain a deeper understanding of their GraphQL data.
=> HttpHeaders as Custom Attributes and GRAPHQL Request Headers Capture

.github/workflows/smokeTests.yml, instrumentation/src/main/java/com/newrelic/agent/compile/ClassTransformer.java, instrumentation/src/main/java/com/newrelic/agent/compile/InvocationDispatcher.java, instrumentation/src/test/java/com/newrelic/agent/compile/ClassTransformerTest.java, plugins/gradle/src/functional/groovy/com/newrelic/agent/android/PluginJDK11SmokeSpec.groovy, plugins/gradle/src/integration/groovy/com/newrelic/agent/android/NewRelicExtensionTest.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/ClassTransformWrapperTask.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/NewRelicExtension.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/NewRelicGradlePlugin.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/VariantConfiguration.groovy, samples/agent-test-app/android.gradle
Caller can provide leading package components ('com.newrelic/android'), or regexp matching strings ('^com.newrelic.a.*$')
* Tests and sample test app updated
* Only supported in Gradle 7.4 and higher at the moment.
=> [NR-24643] Exclude package instrumentation

agent-core/src/main/java/com/newrelic/agent/android/analytics/EventManagerImpl.java, gradle.properties, plugins/gradle/src/main/groovy/com/newrelic/agent/android/BuildHelper.groovy
Ticket [here](https://new-relic.atlassian.net/browse/NR-215814)
1. Upgrade AGP version from 8.2 to 8.4
2. Change DEFAULT_MAX_EVENT_BUFFER_SIZE to 1000 as the default value
**Testing:**
1. Android Studio: JellyFish preview
3. Gradle: 7.6-RC AGP: 8.4.0-alpha04
4. Tested with build and data sent to NR1 all good
=> [NR-215814] v7.2.1 Android Release

agent-core/src/main/java/com/newrelic/agent/android/analytics/EventManagerImpl.java, gradle.properties, plugins/gradle/src/main/groovy/com/newrelic/agent/android/BuildHelper.groovy
**Note:** 
1. The original release/7.2.1 is branched off main
2. When backporting to develop after release, release/7.2.1 is updated with all the commits in develop so we can merge
1. Upgrade AGP support version to 8.4
4. Correct DEFAULT_MAX_EVENT_BUFFER_SIZE to 1000
=> Backport Release/7.2.1 to develop branch

agent-core/src/main/java/com/newrelic/agent/android/logging/LogForwarder.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadSender.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogForwarderTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LoggingTests.java, agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java
LogForwarder is derived fromPayload sender, which is a component of the PayloadController model and understands Vortex response codes. Unlike a PayloadSender, it wraps a file as its data store.
* Refactor PayloadSender to adapt a file-based payload
* Adds tests
Metric Root: "Supportability/AgentHealth/LogReporting" with the following sub-keys:
"Init" - LogReporting feature has started 
"UploadTime" - Duration of upload requests to ingest
"UploadTimeOut" - Count of failed upload attempts due to connect tmeout
"UploadThrottled" - Count of uploads not accepted by ingest due to API limits
"FailedUpload" - Count of upload attempts that fail for otehr reasons
"Expired" - Log data that is removed from use device due to expiration
"Removed/Rejected" - Count of log records that are rejects by the …
=> [NR-178365] Enable Log forwarding to Log Ingest

agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent-core/src/main/java/com/newrelic/agent/android/logging/RemoteLogger.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java, agent/src/test/java/com/newrelic/agent/android/NewRelicTest.java
Fixes a few things discovered in mob:
Maintenance sweep in now done in onHarvestComplete(), which is always
run on a worker thread.
This was a collision with the MVP configuration solution.  Global log level can always be set at any time.
Null messages are replaced by recognizable "empty message"; null attributes maps are replaced with map that contains null message replacement.
Also:
* re-disables that flakey test for later resolution
* dIsables the "minimum payload" size threshold experiment
=> Logging MVP Feedback

agent-core/src/main/java/com/newrelic/agent/android/logging/LogForwarder.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent-core/src/main/java/com/newrelic/agent/android/logging/MessageValidator.java, agent-core/src/main/java/com/newrelic/agent/android/logging/RemoteLogger.java, agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadReporter.java, agent-core/src/main/java/com/newrelic/agent/android/stats/TicToc.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogForwarderTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReportingTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LoggingTests.java, agent-core/src/test/java/com/newrelic/agent/android/logging/MessageValidatorTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java, agent/src/test/java/com/newrelic/agent/android/NewRelicTest.java
LogReporter start call should probably be made when other components are started (after the harvester is established).
* added test
* fixes timer calculations in tests 
For MVP review, null message, attribute and throwable values are translated to recognizable string ("invalid message"), map containing that message, and exception type (IllegalArgumentException).  The goal is to help the customer  (and us) isolate when invalid arguments are passed to the logging methods.
For GA, we may remove this to reduce the amount of data forwarded to ingest.
=> fix: Log reporter not started

agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestConnection.java, agent-core/src/main/java/com/newrelic/agent/android/logging/ForwardingAgentLog.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogForwarder.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent-core/src/main/java/com/newrelic/agent/android/logging/MessageValidator.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent-core/src/main/java/com/newrelic/agent/android/util/Constants.java, agent-core/src/main/java/com/newrelic/agent/android/util/Streams.java, agent-core/src/test/java/com/newrelic/agent/android/logging/ForwardingAgentLogTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/util/StreamsTest.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java, agent/src/main/java/com/newrelic/agent/android/logging/AndroidAgentLog.java
[NR-178365] Pull up agent remote logging into its own class
* add `logger` attribute to indicate log message was sent by the agent
[NR-232439] Support all log collector endpoints
[NR-223199] fix: add missing supportability metric delimiter
chore: refactor request content type and encoder constants
* separates content-type form encoding
* adds GZIP content and encoding type constants
chore: add more stream helpers
* And Javadoc documentation; updated tests
=> [NR-178365] fix: payload overflow resulted in 413 from log collector

agent/src/main/java/com/newrelic/agent/android/NewRelic.java, agent/src/main/java/com/newrelic/agent/android/rum/AppApplicationLifeCycle.java, agent/src/test/java/com/newrelic/agent/android/NewRelicTest.java
Ticket: https://new-relic.atlassian.net/browse/NR-228413
1. Bug Fix: WithLaunchAcitivyName is not captured in AppApplicationLifeCycle class
=> [NR-228513] Bug fix: withLaunchActivityName

.github/workflows/functionalTests.yml
JDK Gradle TestKit blows out heap. This test should have been disabled until fully resolved. We were lucky it ran before, but the dynamic feature merge wasn't vetted for this test.
=> Update functionalTests.yml to disable JDK17 func test

agent-core/src/main/java/com/newrelic/agent/android/agentdata/AgentDataController.java, agent-core/src/main/java/com/newrelic/agent/android/agentdata/AgentDataReporter.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsEvent.java, agent-core/src/main/java/com/newrelic/agent/android/crash/Crash.java, agent-core/src/main/java/com/newrelic/agent/android/crash/CrashReporter.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestTimer.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvester.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java
1. Ticket 1: https://new-relic.atlassian.net/browse/NR-238804
2. Ticket 2: https://new-relic.atlassian.net/browse/NR-238799
3. Ticket 3: https://new-relic.atlassian.net/browse/NR-238759
1. Life the shutdown for agent when goes into background
2. Add attribute when collected data in background --> "background": true
3. Add supportability metrics
4. Verified that applicationstate is updated when app goes to foreground and background.
**Testing**
1. Real device testing: new attributes and new metrics are reported to NR1
2. Limited unit testing scenarios, will add when continue testing
=> Background reporting

agent-core/src/main/java/com/newrelic/agent/android/agentdata/AgentDataReporter.java, agent-core/src/main/java/com/newrelic/agent/android/crash/CrashReporter.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestConnection.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent-core/src/main/java/com/newrelic/agent/android/util/Constants.java
Ticket: https://new-relic.atlassian.net/browse/NR-89226
1. Add supportability metric when payload size > 1MB based on agent spec [here](https://source.datanerd.us/agents/agent-specs/pull/585)
**Testing:**
1. Real device testing
=> [NR-89226] Add supportability metric when size > 1MB for each endpoint

agent-core/src/main/java/com/newrelic/agent/android/stats/TicToc.java, agent-core/src/test/java/com/newrelic/agent/android/stats/TicTocTest.java
Ticket: https://new-relic.atlassian.net/browse/NR-59017
1. Use nanoTime() but covert to millionSeconds due to agent is using ms as default calculation.
2. Add unit tests
=> TicToc time calculation & convertion

.github/workflows/smokeTests.yml, agent-core/src/main/java/com/newrelic/agent/android/AgentConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/FeatureFlag.java, agent-core/src/main/java/com/newrelic/agent/android/agentdata/AgentDataController.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsEvent.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsEventCategory.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsEventFactory.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsValidator.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/ApplicationExitEvent.java, agent-core/src/main/java/com/newrelic/agent/android/crash/Crash.java, agent-core/src/test/java/com/newrelic/agent/android/FeatureFlagTest.java, agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java, agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java, agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java, agent/src/test/java/com/newrelic/agent/android/NewRelicTest.java, agent/src/test/java/com/newrelic/agent/android/test/stub/StubAnalyticsAttributeStore.java, agent/src/test/resources/ApplicationExitInfo.trace, buildconfig.gradle
The agent sweeps for data for app exit info once, during initialization. ApplicationEventInfo records are stored as files in app's cache dir, which also serves to indicate an app exit info entry has been recorded.
Exit info is stored in a new reserved event type and delivered with the first harvest.
* requires upgrade to `compileSdk 30` to support new API
* creates new feature flag `ApplicationExitReporting`
* creates new event category: ApplicationExit
* creates new event type: MobileApplicationExit
* creates new attribute set for event
* adds tests; refactors test code to share stubs
=> [NR-230991] Record ApplicationExitInfo for Android 11+

agent-core/src/main/java/com/newrelic/agent/android/AgentConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/ApplicationExitConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/RemoteConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvester.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent-core/src/test/java/com/newrelic/agent/android/RemoteConfigurationTest.java, agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvestConfigurationTests.java, agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvestableCacheTest.java, agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvesterTest.java, agent-core/src/test/resources/Connect-Spec-PORTED.json, agent-core/src/test/resources/Connect-Spec-v1.json, agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java, agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java, agent/src/main/java/com/newrelic/agent/android/SavedState.java, agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java
Based on agent spec, extract the new "configuration" element from the connect request response body (Json) and propagate to runtime agent configuration. 
By default, AEI config will be **enabled** locally but still gated by feature flag so it can be used prior to config UI/ingest  integration.
=> [NR-247779] Connect remote config to AEI feature

agent-core/src/main/java/com/newrelic/agent/android/ApplicationExitConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent-core/src/test/java/com/newrelic/agent/android/ApplicationExitConfigurationTest.java, agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java, agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java
Adds the standard feature flag API metrics:
* Supportability/Mobile/Android/<framework>/<frameworkVersion>/API/enableFeature/ApplicationExitReporting
* Supportability/Mobile/Android/<framework>/<frameworkVersion>/API/disableFeature/ApplicationExitReporting
And those specific to AEI data:
* Supportability/AgentHealth/ApplicationExitInfo/unsupportedOS/{sdkVersion}
* Supportability/AgentHealth/ApplicationExitInfo/status/{status code}
* Supportability/AgentHealth/ApplicationExitInfo/reason/{reason code}
* Supportability/AgentHealth/ApplicationExitInfo/importance/{importance code}
And those specific to AEI configuration:
* Supportability/AgentHealth/ApplicationExitInfo/remoteConfiguration/{enabled|disabled}
=> [NR-251338] Add supportability metrics for important AEI operations

agent/src/main/java/com/newrelic/agent/android/stores/SharedPrefsEventStore.java
The handling of event storage in shared preferences is not being done correctly, leading to Application Not Responding (ANR) errors and a long delay in saving the events.
=> fix: Event storage in shared preferences causing ANR and delays.

agent-core/src/main/java/com/newrelic/agent/android/AgentConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReportingConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LoggingConfiguration.java, agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvestConfigurationTest.java, agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvesterTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReportingConfigurationTest.java, agent-core/src/test/resources/Connect-Spec-v5.json
Remote logging sampling is assumed to affect the sessioni, so create a random seed at start-up that determines whether this session is sampled. Sampling is enabled when the random seed is less than or equal the configured threshold.
Adds tests.
=> [NR-265384] Implement ingest sampling configuration

agent-core/src/main/java/com/newrelic/agent/android/AgentConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvester.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent-core/src/main/java/com/newrelic/agent/android/logging/RemoteLogger.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LoggingTests.java, agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java, agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java, agent/src/main/java/com/newrelic/agent/android/SavedState.java, agent/src/test/java/com/newrelic/agent/android/NewRelicTest.java, agent/src/test/java/com/newrelic/agent/android/SavedStateTest.java
Working as expected, with a few kinks. Local config updating is awkward and need of refinement. As known, there will always be at least a 1-2 harvest lag in realizing the config changes.
Also, fix missing entity guid hand-off from config response.
Adds/updates tests.
=> [NR-177314] Verify config updates on data harvest

agent-core/src/main/java/com/newrelic/agent/android/logging/ForwardingAgentLog.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java, agent/src/main/java/com/newrelic/agent/android/NewRelic.java
Initialized too early, before the remote logging state was valid.
* fixed ForwardingLog level attribute
=> fix: LogReporter not started with default config

agent-core/src/main/java/com/newrelic/agent/android/measurement/consumer/MetricMeasurementConsumer.java, agent-core/src/test/java/com/newrelic/agent/android/measurement/MetricMeasurementTests.java, agent-core/src/test/java/com/newrelic/agent/android/measurement/consumer/MetricMeasurementTest.java
Ticket: https://new-relic.atlassian.net/browse/NR-235235
1. Remove metrics.clear() from onHarvestError and onHarvestSendFailure
2. Double checked all the .clear() functions
3. Unit tests updated
=> [NR-235235] Only clear metrics when onHarvestComplete

agent-core/src/main/java/com/newrelic/agent/android/stats/StatsEngine.java, agent-core/src/test/java/com/newrelic/agent/android/stats/StatsEngineTest.java, agent/src/main/java/com/newrelic/agent/android/rum/AppApplicationLifeCycle.java
Ticket: https://new-relic.atlassian.net/browse/NR-276058
1. Move clear action of the supportability metrics from onHarvest to onHarvestComplete
=> [NR-276058] Modify when to clear supportability metrics

agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvest.java
While calling Harvest's `shutdown` method, the current checks only consider the nullability of the Harvest instance and it's harvester. But, the  `harvestTimer` is also accessed during the method execution. If the `harvestTimer` is null due to some reason, for instance, a back to back call to the  `shutdown` method, we get a null pointer exception.
Added a null check to prevent this.
This Null pointer exception is one of the top crashes happening in our application. Also attached the stacktrace below.
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void com.newrelic.agent.android.harvest.HarvestTimer.shutdown()' on a null object reference
at com.newrelic.agent.android.harvest.Harvest.shutdownHarvester (Harvest.java:119)
at …
```
=> [NR-308026] Fix Null pointer exception while shutting down harvester

agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent-core/src/main/java/com/newrelic/agent/android/logging/RemoteLogger.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java
Added the following parameters to the log payload for each mobile agent for Instrumentation insights
'instrumentation.provider': 'mobile'
'instrumentation.name': [platform name]
'instrumentation.version': [platform version]
‘collector.name’:[AndroidAgent, iOSAgent]
=> Instrumentation Insights for Log reporting

agent/build.gradle
The builds on GH were resulting in duplicate Kotlin definitions. Should not have been, but were for some reason.
=> fix: no need to delare Kotlin plugin in agent module

.github/workflows/gradlePluginPortalDeployment.yml, .github/workflows/sonatypeDeployment.yml, agent/build.gradle, instrumentation/build.gradle, plugins/gradle/build.gradle, settings.gradle
... using the Gradle Publishing Plugin.
The new plugin was also publishing the `PluginMavenPublication` and `NewrelicPluginPluginMarkerMavenPublication` publications which did not contain valid POMs (the root cause of the deploy failures).
=> [NR-145885] Resolve maven publishing

agent-core/src/main/java/com/newrelic/agent/android/aei/SessionMapper.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java, agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsEvent.java, agent-core/src/test/java/com/newrelic/agent/android/aei/SessionMapperTest.java, agent-core/src/test/java/com/newrelic/agent/android/analytics/AnalyticsEventTests.java, agent/src/main/java/com/newrelic/agent/android/aei/ApplicationExitMonitor.java, agent/src/test/java/com/newrelic/agent/android/aei/ApplicationExitMonitorTest.java
Acceptance criteria:
* a PID-to-session map will be created and persisted in local AEI cache
* for AEI events gathered during the first agent run, the sessionID of the event will be the one that recorded the event
* for AEI events gathered in successive sessions, a new attribute will be added to provide the session ID in which the AEI occurred 
* in this case session ID will never match recorded session ID
* session ID map will be updated each time the agent starts
* session ID map will be updated each time the agent restarts
* session ID map will be pruned when the set of AEI records returned by the ART no longer includes elements in the map
* an attribute with the historic session ID will be inserted into the event as `sessionId`.
Tests will be created to reflect this criteria.
=> [NR-331312] Add AEI session mapper

agent-core/src/main/java/com/newrelic/agent/android/AgentConfiguration.java, agent-core/src/main/java/com/newrelic/agent/android/aei/AEITrace.java, agent-core/src/main/java/com/newrelic/agent/android/aei/AEITraceReporter.java, agent-core/src/main/java/com/newrelic/agent/android/aei/AEITraceSender.java, agent-core/src/main/java/com/newrelic/agent/android/aei/SessionMapper.java, agent-core/src/main/java/com/newrelic/agent/android/crash/CrashSender.java, agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java, agent-core/src/main/java/com/newrelic/agent/android/payload/FileBackedPayload.java, agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadController.java, agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadSender.java, agent-core/src/test/java/com/newrelic/agent/android/aei/AEITraceReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/aei/AEITraceSenderTest.java, agent/src/main/java/com/newrelic/agent/android/aei/ApplicationExitMonitor.java, agent/src/test/java/com/newrelic/agent/android/aei/ApplicationExitMonitorTest.java
Following the existing store-and-forward pattern used by log reporting, add a new reporter and sender component to manage AEI trace uploads. Traces are cached to disk, uploaded during harvest cycles and removed from disk once the upload is successful or has expired.
=> [NR-293384] AEI Trace Reporting

agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java, agent/src/test/java/com/newrelic/agent/android/instrumentation/LogInstrumentationTest.java
=> Null Throwable are generating repetitive logs in Console.

agent-core/src/main/java/com/newrelic/agent/android/aei/AEISessionMapper.java, agent-core/src/test/java/com/newrelic/agent/android/aei/AEISessionMapperTest.java, agent/src/main/java/com/newrelic/agent/android/aei/ApplicationExitMonitor.java, agent/src/test/java/com/newrelic/agent/android/aei/ApplicationExitMonitorTest.java
AEI event requests now depend on the historic _real agent ID_ as well.
=> [NR-337308] Add realAgentId to historic AEI metadata

build.gradle
Fixes
```
P:\projects\contrib\github-newrelic-android-agent>gradlew build
Picked up JAVA_TOOL_OPTIONS: -Xms32M -Xmx256M -D-XX:+UseG1GC -D-XX:+PrintCommandLineFlags
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.6/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Configure project :instrumentation
[newrelic] [instrumentation] Recompiling [P:\projects\contrib\github-newrelic-android-agent\instrumentation\build/tmp/compileJava/src/main/java/com/newrelic/agent/InstrumentationAgent.java]
[newrelic] [instrumentation] Stamping [P:\projects\contrib\github-newrelic-android-agent\instrumentation\src\main\java/com/newrelic/agent/InstrumentationAgent.java] into …
```
=> Support Windows for external builds

agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtil.java, agent-core/src/test/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtilTest.java
This Pull Request resolves an issue where original HTTP headers were captured, but the modified headers after the interceptor were not.
NR-356696
#210
=> fix:Capture Modified HTTP Headers in Interceptor

plugins/gradle/src/integration/groovy/com/newrelic/agent/android/DexGuardHelperTest.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/agp4/AGP4Adapter.groovy, plugins/gradle/src/main/groovy/com/newrelic/agent/android/agp7/AGP70Adapter.groovy
android clean build command is failed because of variant dirname missing from the newer agp api.
=> fix android build issue

agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvester.java, agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java, agent-core/src/main/java/com/newrelic/agent/android/logging/RemoteLogger.java, agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java, agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java, agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java, agent/src/main/java/com/newrelic/agent/android/util/OfflineStorage.java, agent/src/main/java/com/newrelic/agent/android/util/PersistentUUID.java, gradle.properties
Ticket: [NR-409074](https://new-relic.atlassian.net/browse/NR-409074)
1. Log reporting files are backed up instead of deleting, could be the potential cause of ANRs, changing it to a deletion process.
2. We are only using two files at time to write into data and upload to the server.
3. Remove the size checking of 1MB because we are using gzip when uploading.
4. Added cleanup process onHarvestStart
5. Truncated messages issues: partially fixed, still need to fix the race condition issue on every harvest cycle with background reporting on/off.
6. Warning message: resources may not be closed? - this is our logwriter, we need to leave it open for log writing but will see how we can improve it.
[NR-409074]: https://new-relic.atlassian.net/browse/NR-409074?atlOrigin=eyJpIjoiNWRk …
=> NR-409074 Log ANRs Fix

README.md
Updating README
I noticed the setup instructions were outdated. the "Android SDK section has been moved in the settings to `Language & Frameworks`
=> feat: Update AndroidStudio setup Section in Readme

agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3Instrumentation.java, agent-core/src/test/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtilTest.java, gradle.properties, gradle/publishing_aar.gradle
When OkHttp3 interceptors modify the request URL, the New Relic Android agent now correctly reports the final, modified URL. This is achieved by adding a New Relic interceptor after all existing client interceptors. This interceptor captures the final URL from the request chain and updates the transaction state accordingly.
=> [NR-300843]Fix: OkHttp3 Url updated by interceptors
