newrelic/newrelic-android-agent

.github/workflows/repolinter.yml

chore: repolinter configuration
Fixes https://github.com/newrelic/newrelic-android-agent/issues/105

chore: repolinter configuration

---

agent-core/src/main/java/com/newrelic/agent/android/util/NamedThreadFactory.java

First of several commits to address Android SDK deprecations in agent code.

[NR-98179] fix: update deprecated thread security code

---

plugins/gradle/src/main/groovy/com/newrelic/agent/android/ClassTransformWrapperTask.groovy

This was a check we needed to do in older agent versions, but no longer necessary in the the new Android AGP model. Will add test when I figure out how.

[NR-150482] fix: remove JAR signing checks from class transform wrapper

---

plugins/gradle/src/main/groovy/com/newrelic/agent/android/ClassTransformWrapperTask.groovy

This is not a bug, but rather a side-effect of AGP's instrumentation model. Prior, JAR files were rewritten in place, and with updated model all instrumented classes to into the same JAR. So if dependencies share the same package names, manifest and directory entries will be rejected as duplicates when processed. As long as these aren't class files, the error is misleading.

[NR-152229] Silence "duplicate entry" errors during instrumentation

---

.github/bin/trimWorkflowRuns
.github/workflows/workflowCleanup.yml

Also adds adds workflow job to be run at the beginning of each month.
NOTE: script is set for _dryrun_, meaning no data will be deleted until all changes are verified.

chore: add script to bulk delete GHA workflow runs

---

plugins/gradle/src/functional/groovy/com/newrelic/agent/android/PluginSpec.groovy

Fixes broken functional regression tests

fix: remove Jetpack test app from the functional test spec

---

.github/workflows/codecov.yml
agent-core/build.gradle
agent/build.gradle
build.gradle
buildconfig.gradle
instrumentation/build.gradle
jacoco.gradle
plugins/gradle/build.gradle

**SQUASH TO MERGE**
1. Added codecov for all modules
2. Create GHA task

[NR-165205] Add codecov

---

plugins/gradle/src/main/groovy/com/newrelic/agent/android/ClassTransformWrapperTask.groovy

Bug fix: https://issues.newrelic.com/browse/NR-168456

[NR-168456] Exception handling around classTransformer

---

agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java
agent-core/src/test/java/com/newrelic/agent/android/logging/LogReportingTest.java

* adds log levels, level methods and stub `notice()` method.

[NR-121370] Add remote logging interface

---

agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestConfiguration.java
agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java
agent/src/main/java/com/newrelic/agent/android/NewRelic.java

1. Temp solution for client side to setEntityGuid
2. Tested with apps, didn't write unit test as this will be removed later

Temp Solution to setEntityGuid

---

.github/workflows/android.yml
.github/workflows/codecov.yml

android.yml and codecov.yml now respond to feature branches

chore: allow validation tasks to run manually (workflow dispatch)

---

agent-core/src/main/java/com/newrelic/agent/android/FeatureFlag.java
agent-core/src/test/java/com/newrelic/agent/android/FeatureFlagTest.java

Ticket [here](https://new-relic.atlassian.net/browse/NR-238665)
1. FeatureFlag: BackgroundReporting
2. Added feature flag and unit tests

[NR-238665] add backgroundReporting feature flag and tests

---

agent/src/main/java/com/newrelic/agent/android/NewRelic.java
agent/src/main/java/com/newrelic/agent/android/stores/SharedPrefsEventStore.java
agent/src/main/java/com/newrelic/agent/android/stores/SharedPrefsStore.java

fix: offline storage anr issue and excessive string concatenation

---

agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java
agent/src/test/resources/ApplicationExitInfo.trace

Implied business rules: adds new `appState` String attribute whose value is either `foreground` or `background` based on value of AEI importance value.
* Adds/updates tests

[NR-259770] Translate AEI importance value to foregroud/background state

---

agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java

1. We would like to report all reasons rather than just ANR reason
2. Modify existing unit tests

[NR-247776] Report AEI all reasons

---

agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java

Ticket: https://new-relic.atlassian.net/browse/NR-264510
1. Remove trace reporting from AEI implementation
2. Fix unit tests

[NR-264510] Remove trace reporting from AEI implementation

---

agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java

https://docs.google.com/document/d/1jJQkaLpTb-2eVee_xKOwxSw4kILJDar8yZJfPo347u4/edit?usp=sharing

[NR-258647] chore: cleanup from docs edit

---

agent-core/src/main/java/com/newrelic/agent/android/AgentConfiguration.java
agent-core/src/main/java/com/newrelic/agent/android/ApplicationExitConfiguration.java
agent-core/src/main/java/com/newrelic/agent/android/RemoteConfiguration.java
agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestConfiguration.java
agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvester.java
agent-core/src/main/java/com/newrelic/agent/android/logging/LogLevel.java
agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java
agent-core/src/main/java/com/newrelic/agent/android/logging/LogReportingConfiguration.java
agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java
agent-core/src/test/java/com/newrelic/agent/android/RemoteConfigurationTest.java
agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvestConfigurationTests.java
agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvestableCacheTest.java
agent-core/src/test/java/com/newrelic/agent/android/harvest/HarvesterTest.java
agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java
agent-core/src/test/java/com/newrelic/agent/android/logging/LogReportingTest.java
agent-core/src/test/java/com/newrelic/agent/android/test/mock/Providers.java
agent-core/src/test/resources/Connect-Spec-PORTED.json
agent-core/src/test/resources/Connect-Spec-v1.json
agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java
agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/main/java/com/newrelic/agent/android/NewRelic.java
agent/src/main/java/com/newrelic/agent/android/SavedState.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java
agent/src/test/java/com/newrelic/agent/android/NewRelicTest.java
gradle.properties

Merging remote logging configuration support.

[NR-239869] Mobile Logging - alpha02

---

agent-core/src/main/java/com/newrelic/agent/android/FeatureFlag.java
agent-core/src/main/java/com/newrelic/agent/android/agentdata/AgentDataController.java
agent-core/src/main/java/com/newrelic/agent/android/agentdata/AgentDataReporter.java
agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsEvent.java
agent-core/src/main/java/com/newrelic/agent/android/crash/Crash.java
agent-core/src/main/java/com/newrelic/agent/android/crash/CrashReporter.java
agent-core/src/main/java/com/newrelic/agent/android/harvest/HarvestTimer.java
agent-core/src/main/java/com/newrelic/agent/android/harvest/Harvester.java
agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java
agent-core/src/test/java/com/newrelic/agent/android/FeatureFlagTest.java
agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java

Ticket: https://new-relic.atlassian.net/browse/NR-169834
1. lift the shutdown process when app goes into the background
2. add feature flag: BackgroundReporting, disabled as default
3. add attribute to capture background reported data using new attribute
4. add supportability metrics to match with both platforms

[NR-169834] Background reporting feature

---

agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java

Ticket: https://new-relic.atlassian.net/browse/NR-279827
1. Translate importance as an integer to it's string value
2. Add unit tests

Translate importance int to string

---

agent-core/src/main/java/com/newrelic/agent/android/metric/MetricNames.java
agent/src/main/java/com/newrelic/agent/android/ApplicationExitMonitor.java
agent/src/main/java/com/newrelic/agent/android/NewRelic.java
agent/src/test/java/com/newrelic/agent/android/ApplicationExitMonitorTest.java

NR-251338: adds method to translate reason code. For testing and SM's, not added as event attribute at the moment.

chore: Tune AEI supportability metrics

---

agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporting.java
agent-core/src/main/java/com/newrelic/agent/android/logging/RemoteLogger.java
agent-core/src/test/java/com/newrelic/agent/android/logging/RemoteLoggerTest.java
gradle.properties

Ticket: https://new-relic.atlassian.net/browse/NR-292881
1. Add sessionId attribute to logging
2. Add unit tests

[NR-292881] add sessionId attribute to logging

---

agent-core/src/main/java/com/newrelic/agent/android/crash/Crash.java
agent-core/src/main/java/com/newrelic/agent/android/crash/CrashReporter.java
agent-core/src/main/java/com/newrelic/agent/android/harvest/DataToken.java
agent-core/src/test/java/com/newrelic/agent/android/crash/CrashReporterTests.java
agent-core/src/test/java/com/newrelic/agent/android/test/mock/Providers.java

Agent is sending newer data token with Crash Created in Older version of the app.

fix: Agent Version and App Build Id Mismatch After App Update

---

.github/workflows/gradlePluginPortalDeployment.yml
agent-core/src/main/java/com/newrelic/agent/android/metric/Metric.java
agent/build.gradle
buildconfig.gradle
gradle.properties
gradle/publishing.gradle
instrumentation/build.gradle
plugins/gradle/build.gradle
plugins/gradle/src/main/groovy/com/newrelic/agent/android/BuildHelper.groovy
settings.gradle

GPP requires a new ID: `com.newrelic.agent.android`, and would be applied as
```
plugins {
id 'com.newrelic.agent.android' version '<version>'
}
```

[NR-145885] Support Gradle Plugin Portal

---

agent-core/src/main/java/com/newrelic/agent/android/aei/AEITrace.java
agent-core/src/test/java/com/newrelic/agent/android/aei/AEITraceTest.java
agent-core/src/test/resources/applicationExitInfo/systrace
agent-core/src/test/resources/applicationExitInfo/traceThreads

* parses system trace provided by AEI record into thread collection
* adds tests

[NR-315570] Add AEI trace model

---

agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadReaper.java
agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadSender.java
agent-core/src/test/java/com/newrelic/agent/android/agentdata/AgentDataSenderTest.java
agent-core/src/test/java/com/newrelic/agent/android/crash/CrashReporterTests.java
agent-core/src/test/java/com/newrelic/agent/android/crash/CrashSenderTest.java
agent-core/src/test/java/com/newrelic/agent/android/crash/UncaughtExceptionHandlerTest.java
agent-core/src/test/java/com/newrelic/agent/android/logging/LogForwarderTest.java
agent-core/src/test/java/com/newrelic/agent/android/payload/PayloadControllerTest.java
agent-core/src/test/java/com/newrelic/agent/android/payload/PayloadReaperTest.java
agent-core/src/test/java/com/newrelic/agent/android/payload/PayloadReporterTest.java
agent-core/src/test/java/com/newrelic/agent/android/payload/PayloadSenderTest.java
agent-core/src/test/java/com/newrelic/agent/android/payload/PayloadStoreTest.java

Since we've been sing the new vpn, some tests fail due to odd networking exceptions in Mockito.
* DRY's up connection mocking code

chore: cleanup tests

---

agent-core/src/main/java/com/newrelic/agent/android/aei/AEITraceSender.java
agent-core/src/main/java/com/newrelic/agent/android/payload/FileBackedPayload.java
agent-core/src/main/java/com/newrelic/agent/android/util/Constants.java
agent-core/src/test/java/com/newrelic/agent/android/aei/AEITraceSenderTest.java
agent-core/src/test/java/com/newrelic/agent/android/payload/FileBackedPayloadTest.java

* update AEITraceSender tests
* exposed FileBackedPayload `compress()` methods, updates tests

[NR-293384] Update request header

---

agent-core/src/main/java/com/newrelic/agent/android/aei/AEISessionMapper.java
agent-core/src/main/java/com/newrelic/agent/android/logging/LogForwarder.java
agent-core/src/main/java/com/newrelic/agent/android/payload/PayloadSender.java
agent-core/src/test/java/com/newrelic/agent/android/aei/AEITraceTest.java
agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java
agent/src/main/java/com/newrelic/agent/android/aei/ApplicationExitMonitor.java

1) ANR is not sent when Session Map is Empty
2) ANR's  SessionMap is not updated when app goes foreground and background multiple times.

fix: ANR fixes

---

agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java

fix:Android logs are not being sent regularly

---

plugins/gradle/src/main/groovy/com/newrelic/agent/android/BuildHelper.groovy

Ticket: https://new-relic.atlassian.net/browse/NR-370929
1. Upgrade max supported AGP version to 8.8.

[NR-370929] Upgrade AGP version

---

agent-core/src/main/java/com/newrelic/agent/android/AgentImpl.java
agent-core/src/main/java/com/newrelic/agent/android/NullAgentImpl.java
agent-core/src/main/java/com/newrelic/agent/android/agentdata/HexAttribute.java
agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsAttribute.java
agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsControllerImpl.java
agent-core/src/main/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtil.java
agent-core/src/test/java/com/newrelic/agent/android/instrumentation/okhttp3/OkHttp3TransactionStateUtilTest.java
agent-core/src/test/java/com/newrelic/agent/android/logging/LogReporterTest.java
agent-core/src/test/java/com/newrelic/agent/android/test/stub/StubAgentImpl.java
agent/src/main/java/com/newrelic/agent/android/AndroidAgentImpl.java
agent/src/main/java/com/newrelic/agent/android/aei/ApplicationExitMonitor.java
gradle.properties
plugins/gradle/src/main/groovy/com/newrelic/agent/android/BuildHelper.groovy

Ticket: https://new-relic.atlassian.net/browse/NR-371135
[NR-364617](https://new-relic.atlassian.net/browse/NR-364617)
[NR-356696](https://new-relic.atlassian.net/browse/NR-356696)
[NR-371138](https://new-relic.atlassian.net/browse/NR-371138)
[NR-370929](https://new-relic.atlassian.net/browse/NR-370929)
[NR-364617]: https://new-relic.atlassian.net/browse/NR-364617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NR-356696]: https://new-relic.atlassian.net/browse/NR-356696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NR-371138]: https://new-relic.atlassian.net/browse/NR-371138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NR-370929]: …

[NR-371135] Android Agent Release v7.6.4

---

agent-core/src/main/java/com/newrelic/agent/android/instrumentation/TransactionState.java
agent-core/src/main/java/com/newrelic/agent/android/stats/StatsEngine.java
agent-core/src/main/java/com/newrelic/agent/android/tracing/TraceMachine.java
gradle.properties
instrumentation/src/main/java/com/newrelic/agent/InstrumentationAgent.java
instrumentation/src/main/java/com/newrelic/agent/compile/ClassTransformer.java
instrumentation/src/main/java/com/newrelic/agent/compile/InvocationDispatcher.java
instrumentation/src/test/java/com/newrelic/agent/compile/InvocationDispatcherTest.java
plugins/gradle/src/main/groovy/com/newrelic/agent/android/NewRelicExtension.groovy
plugins/gradle/src/main/groovy/com/newrelic/agent/android/NewRelicGradlePlugin.groovy

[NR-336238] fix: added build time feature flag for default interaction 

---

agent-core/src/main/java/com/newrelic/agent/android/logging/LogReporter.java

Ticket: [NR-382847](https://new-relic.atlassian.net/browse/NR-382847)
1. Added onHarvestConnected in log reporting to cover the case of submitting remaining logs when app terminates 
[NR-382847]: https://new-relic.atlassian.net/browse/NR-382847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NR-382847] Report log upon app termination

---

agent-core/src/main/java/com/newrelic/agent/android/util/Streams.java

Ticket: [NR-376107](https://new-relic.atlassian.net/browse/NR-376107)
What is changed:
1. Fixed few violation when strictMode is on during development
2. Followup with a ticket to fix other violations if possible
[NR-376107]: https://new-relic.atlassian.net/browse/NR-376107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

StrictMode Violation Fix

---

agent-core/src/main/java/com/newrelic/agent/android/measurement/CustomMetricMeasurement.java
agent-core/src/main/java/com/newrelic/agent/android/measurement/MeasurementPool.java
agent-core/src/main/java/com/newrelic/agent/android/measurement/producer/BaseMeasurementProducer.java

Ticket: https://new-relic.atlassian.net/browse/NR-438547
1. See ticket for more detailed background and investigation information.
2. Customer cannot provide a reproduce case, neither we can reproduce it. 
3. Debug through the process, clean up the code to make it more straightforward, and then we will monitor it.

[NR-438547] RecordMetric Investigate
